@startuml sender-flags
title Flow: Sender (Flag Mode)

actor User
participant "LocalLoad Tool" as Tool
participant "Network/Peer" as Peer

User -> Tool : Execute: localload -s 12345 -p 22222 -f "hello.txt"
Tool -> Tool : Enter sender mode
Tool -> Tool : Use number 12345
Tool -> Tool : Use file path "hello.txt"
Tool -> Tool : Use receiver number 22222

loop Until connection established with peer
    Tool -> Peer : Search for peer
    Tool -> Peer : Attempt connection
    Tool <-> Peer : Exchange numbers
    alt
        Tool -> Tool : Valid peer number continue
    else
        Tool -> Tool : Invalid number repeat loop
    end
end





Tool -> Tool : Wait for message "you can send"
Peer -> Tool : Receive message "you can send"
Tool -> Peer : Send files
Peer -> Tool : Receive message "finished"
Tool -> Peer : End connection
Tool -> User : End


@enduml
